# Generated by Django 3.0.2 on 2020-01-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csv_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('address', models.TextField()),
                ('email', models.EmailField(default='', max_length=40)),
                ('m_no', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
